### PR TITLE
Issue/229 – Jigoshop coupon tracking

### PR DESCRIPTION
**Pull request by DrewAPicture**
Issue: #229 

Closed #1203 to adjust admin css to accommodate affiliate user autocomplete in side-sortable metaboxes. The `position: absolute;` rule was pushing the autocomplete results off the page.

See 49548d7.

### CODE REVIEW

**Comment by DrewAPicture** [comment]
Before 49548d7:

Bad meta box styles

After 49548d7:

Fixed meta box styles

**Comment by pippinsplugins** [comment]
Looks good to me.

**Comment by DrewAPicture** [comment]
Confirmed that associating an affiliate with a created Jigoshop coupon awards a referral following successful checkout. Looks good.

**Comment by michaelbeil** [comment]
Things look good here.

**Pull request merged**
