### PR TITLE
Instantiate all objects on plugins_loaded

### PR DESCRIPTION
**Pull request by ryanduff**
For sanity... while we still can.

### CODE REVIEW

**Comment by ryanduff** [comment]
I need to put more eyes on this. Overall things seem to work, but getting a fatal error on plugin activation.

Looks to be happening because of how register_activation_hook() runs early and the objects aren't instantiated til plugins_loaded.

**Comment by ryanduff** [comment]
Added 2 more commits to handle install/upgrade and avoid fatal errors.

**Comment by pippinsplugins** [comment]
Looks good to me. I'm going to test further and then merge if all is well.

**Comment by pippinsplugins** [comment]
All Pro add-ons are working fine.

**Pull request merged**
