### PR TITLE
issue/2188 – Double escaping

### PR DESCRIPTION
**Pull request by tivnet**
Issue: #2188

Duplicate `esc_html` ?

### CODE REVIEW

**Comment by DrewAPicture** [comment]
Definitely seems like a duplicate. Nice catch!

@tivnet One thing, can you change the additional return type to `false` instead of `bool`? We like to be as specific as possible :-)

**Comment by tivnet** [comment]
@DrewAPicture Done.

**Comment by DrewAPicture** [comment]
Awesome. We'll merge this as part of the 2.1 release. Thanks for the PR!

**Comment by DrewAPicture** [comment]
Created #2188 for posterity.

**Pull request merged**
