### PR TITLE
issue/1080 – Reference the Affiliate ID and/or link in the order details for several integrations

### PR DESCRIPTION
**Pull request by DrewAPicture**
Issue: #1080

### CODE REVIEW

**Comment by pippinsplugins** [comment]
@tubiz could you please submit a new PR for this that merges cleanly?

**Comment by tubiz** [comment]
@pippinsplugins working on it.

**Comment by michaelbeil** [comment]
This was taken care of in this PR: https://github.com/AffiliateWP/AffiliateWP/pull/2703

**Comment by michaelbeil** [comment]
Closing, since this was taken care of in this PR: https://github.com/AffiliateWP/AffiliateWP/pull/2703

**Pull request closed without merging**
