### PR TITLE
Allow the affiliate status to be set when creating affiliate accounts…

### PR DESCRIPTION
**Pull request by pippinsplugins**
…. #603

### CODE REVIEW

**Comment by sumobi** [comment]
@pippinsplugins inactive and pending aren't working for me

**Comment by pippinsplugins** [comment]
Hmmm, works fine for me.

**Comment by sumobi** [comment]
Will give it another test

**Comment by sumobi** [comment]
@pippinsplugins "pending" works, but only when `Require approval` is enabled. Are there unpushed changes to issue/603 perhaps? Currently it looks like there have been no changes, `affwp_set_affiliate_status` is still setting the affiliate status to either pending or active inside `affwp_add_affiliate()`.

**Comment by pippinsplugins** [comment]
Ah! I'll test again

**Comment by pippinsplugins** [comment]
@sumobi Ready for testing again.

**Comment by sumobi** [comment]
@pippinsplugins as per https://github.com/affiliatewp/AffiliateWP/issues/603 this is all good

**Pull request merged**
