### PR TITLE
Add emails class

### PR DESCRIPTION
**Pull request by ghost1227**
Issue #392

This is NOT ready to be merged. This is solely being posted so I can get feedback from @pippinsplugins on a few things. IE: I'm currently instantiating a second email object (`$email` vs `$emails`) to maintain backwards compatibility. Is that ok in your book? Also, all previous classes are created as `Affiliate_WP_x`, but the issue indicated the new class be `AffWP_Emails`... was that your intention or do you prefer to stick with the original scheme? If we stick with the original scheme, we're conflicting with the existing emails class. Thoughts?

### CODE REVIEW

**Comment by pippinsplugins** [comment]
It should use `Affiliate_WP_Emails` as the class name.

**Comment by pippinsplugins** [comment]
Your new class needs to be merged with the existing emails class. They are to be the same class.

That also means there is no need for a second instance.

**Comment by pippinsplugins** [comment]
Note: this also needs to add the template files and necessary settings.

**Comment by ghost1227** [comment]
Already got much of the settings/template written. Just wanted clarification on the conflicts with the old class.

**Comment by ghost1227** [comment]
@pippinsplugins Is this looking better so far?

**Comment by pippinsplugins** [comment]
Looking good.

Would you be interesting in combining email tags and emails into a single class instead of two separate ones? It was done that way in EDD because email tags came first. Since we're doing them at the same time, we can combine them.

**Comment by ghost1227** [comment]
Personally, I think it makes sense to keep them separate. Emails handles the actual construction and sending of the email, tags is about parsing email tags specifically. That said... it's your show.

**Comment by pippinsplugins** [comment]
Andrew and I just chatted on it: one class please.

**Comment by ghost1227** [comment]
@pippinsplugins how's that?

**Comment by pippinsplugins** [comment]
Initially looks good. I'll have to play with it to say for sure.

One thing I know we'll need is support for affiliate ID and referral IDs in the email tag callbacks, but it wouldn't be for all callbacks, just some.

**Comment by ghost1227** [comment]
I might need a bit of help. I've migrated the actions to the new structure, but I'm starting to get confused looking at the notification function itself. Not like I don't understand what it's doing... just having trouble focusing.

**Comment by pippinsplugins** [comment]
Walk me through what part doesn't make sense and I"ll be happy to help.

**Comment by ghost1227** [comment]
All we have left to convert is merging the old notification function into the new class, and finishing up templates and default tags.

**Comment by pippinsplugins** [comment]
The only thing you need to do with the existing notifications is make it so
that they use the new email templates.

**Comment by ghost1227** [comment]
Are you referring to the notification function? https://github.com/affiliatewp/AffiliateWP/blob/master/includes/class-emails.php#L52

**Comment by pippinsplugins** [comment]
That should be able to remain unchanged. Just updated the send() function:
https://github.com/affiliatewp/AffiliateWP/blob/master/includes/class-emails.php#L120

**Comment by ghost1227** [comment]
@pippinsplugins too late... I merged it into the new class with a few small tweaks. Hopefully you don't object to the tweaks (mostly pulling data from settings so things aren't hardcoded).

**Comment by pippinsplugins** [comment]
No worries, we can always adjust if needed. So with that, what questions or
issues do you have?

**Comment by ghost1227** [comment]
@pippinsplugins Two questions at the moment... first, why aren't those tags getting added/displayed correctly? I'm missing something, but I can't figure out what. Second, not all tags are relevant to all emails. Notably, the amount tag is only valid on new referral emails. How do you want to handle displaying said tags in the settings page?

**Comment by pippinsplugins** [comment]
I really don't have an answer for how to handle the different types of tags (affiliates vs referrals). I'll think more on that.

Are none of the tags working? What happens with them? Just blank?

Looks like the actual template files have not been committed: https://github.com/affiliatewp/AffiliateWP/pull/558/files - Can you make sure you've added them?

**Comment by ghost1227** [comment]
Haven't tested tag functionality, but display is returning nothing. It seems that the variable isn't being set somewhere, but I can't track down the bug.

screen shot 2015-03-09 at 8 11 14 pm

**Comment by pippinsplugins** [comment]
have you stepped through line by line and var_dump()'ed it?

Also, see my note about the template files?

**Comment by ghost1227** [comment]
I saw your note, I'm still trying to figure out how to handle template files. In EDD, we only have one template file (for receipts). In AffWP, we have three potential emails we need to work with. Do we have preview/test actions for all three? Allow selection of template for all three? Should any be text-only like the EDD admin notices are now? Do we do logos per-email, or just assume all use the same logo? There's a LOT more complexity in supporting three templates than one.

**Comment by pippinsplugins** [comment]
It's exactly the same. There are three files: header, body, footer.

**Comment by pippinsplugins** [comment]
Sorry one difference: no need for template select in settings

**Comment by ghost1227** [comment]
So we're only supporting one template? Not allowing HTML vs text? What about logos?

**Comment by pippinsplugins** [comment]
Correct: one HTML template only. Yes to logso.

**Comment by ghost1227** [comment]
Ok... In EDD, header/body/footer are all in one file (templates.php). You said three files. Do you want them split out in AffWP?

**Comment by pippinsplugins** [comment]
Three files:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/tree/master/templates/emails
(look at -default)

**Comment by sumobi** [comment]
@ghost1227 just testing now. So far:

1. Typo

    PHP Fatal error:  Call to undefined function apply_filter() in /wp-content/plugins/affiliatewp-master/includes/emails/class-affwp-emails.php on line 165

2. This would have come over from EDD, seen this one before.

PHP Notice:  wp_editor() was called with an argument that is <strong>deprecated</strong> since version 3.9! TinyMCE editor IDs cannot have brackets.

**Comment by sumobi** [comment]
Typo: "Contratulations"

**Comment by ghost1227** [comment]
@sumobi All those fixed...

**Comment by ghost1227** [comment]
The amount tag, being the only tag that applies JUST to the affiliate notification email, requires a parameter that no other tag does. I'm not sure how to pass it. This also screws up the html list output on the settings page.. amount lists on all emails, though it only applies to one. Not sure the best way to handle it.

**Comment by pippinsplugins** [comment]
Resubmit to `issue/392` please.

**Pull request closed without merging**
