### PR TITLE
Update to resolve secondary submission on Ninja Forms Integrations

### PR DESCRIPTION
**Pull request by Much2tall**
Updated logic to prevent a second submission from taking place when submission ID is already set.

### CODE REVIEW

**Comment by Much2tall** [comment]
closes issue #2057.

**Comment by Much2tall** [comment]
Submitted this code to solve a user's issue.
Awaiting testing by user.

**Comment by Much2tall** [comment]
User responded with Issue Resolved.

**Comment by Much2tall** [comment]
@ramiabraham any movement on this?

**Comment by michaelbeil** [comment]
Could you tell us the steps to reproduce this issue?

**Comment by Much2tall** [comment]
The issue is that the integration with Ninja Forms creates an additional (unnecessary) submission in the database because it does not check to see if it already has a submission in memory.

The only lines with actual changes are the following:

121, 158, 161

Everything else is just a change in indentation.

However, due to the age of the PR, it's possible that this might have been solved in a different way. I only even noticed this because I was cleaning out my PRs last week and found it.

**Comment by Much2tall** [comment]
Still waiting on movement here.

**Comment by pippinsplugins** [comment]
@Much2tall apologies for missing this! I'm working on testing the bug fix now and will merge it once I confirm it works properly.

**Comment by pippinsplugins** [comment]
Fix confirmed, merged!

**Pull request merged**
