### PR TITLE
issue/1345 - Add filters to dashboard statistics to allow add-ons to remove sections

### PR DESCRIPTION
**Pull request by clickstudio**
I have added 3 filters so add-ons can remove statistics sections.

I have also moved the actions outside of the section divs so they are not affected by the filters.

### CODE REVIEW

**Comment by michaelbeil** [comment]
Closing per @pippinsplugins comment here: https://github.com/AffiliateWP/AffiliateWP/issues/1345#issuecomment-224726284

**Comment by clickstudio** [comment]
Hi @michaelbeil and @pippinsplugins 

I appreciate that it's possible to modify the sections using a template however templates are obviously theme dependent and also require the user to have basic knowledge to implement.

The add-on I am working on requires custom statistics so I thought it may be easier to allow the changes via the plugin settings rather than expecting all users to manage template files.

I'm happy either way, just thought is may be a good idea.

**Comment by pippinsplugins** [comment]
Can you tell me a bit more about the add-on?

**Comment by clickstudio** [comment]
Sure thing @pippinsplugins 

I'll email you directly if that's ok ?
Iv'e been meaning to ask your opinion on a few things related to it anyway.

**Pull request closed without merging**
