### PR TITLE
issue/1343 - Add 'affwp_insert_pending_referral' filter to RCP integration

### PR DESCRIPTION
**Pull request by clickstudio**
Issue: #1343

This will bring the integration inline with all other integrations who use this filter.

Could also just use 'insert_pending_referral()' here which fires the filter ?????

I have not tested this.
I am developing an add-on that requires the filter and noticed it was missing for this integration.

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Looks good! We'll get it merged in!

**Comment by clickstudio** [comment]
Thanks @pippinsplugins :-)

**Comment by michaelbeil** [comment]
#1343

**Comment by DrewAPicture** [comment]
@clickstudio Looks pretty good. Fixed a couple of notices in #1483 as a continuation of this PR. Closing in favor of that.

**Pull request closed without merging**
