### PR TITLE
Ready for Grunt + New pot + French l10n

### PR DESCRIPTION
**Pull request by fxbenard**
@pippinsplugins as requested #796

You should run a grunt task to update the pot (18 days old) after

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Awesome, thanks so much!

**Comment by pippinsplugins** [comment]
@fxbenard I got this after running makepot:

https://cloudup.com/cJ6zf3zGTWQ

Any idea?

**Comment by fxbenard** [comment]
Seems to be an error of gettext install on your mac and a conflict with the makepot task.

Change the https://github.com/affiliatewp/AffiliateWP/blob/release/1.7/grunt/makepot.js/#19 to false to stop the auto-update of po files ;)

Run a grunt build:i18n

**Comment by michaelbeil** [comment]
I see no issues here on my end. http://beil.io/19mKc

@pippinsplugins have you installed gettext with homebrew? `brew install gettext`

**Comment by pippinsplugins** [comment]
@michaelbeil I did that but did't make any difference.

@fxbenard I'd like po files to be updated I think.

**Comment by fxbenard** [comment]
@pippinsplugins until you fix your gettext problem check out #839 and you'll get them

@michaelbeil yep same here, same as http://beil.io/19mKc, thanks for the check

**Comment by michaelbeil** [comment]
@pippinsplugins does a `brew upgrade && brew update` do the trick?

**Comment by pippinsplugins** [comment]
No bueno.

**Pull request merged**
