### PR TITLE
issue/1184 – Reduce false positives in get/set/save for objects

### PR DESCRIPTION
**Pull request by DrewAPicture**
Issue: #1184 

These adjustments were curated via troubleshooting issues in #854.

Tests coming up.

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Looks good to me.

**Comment by DrewAPicture** [comment]
Added tests. Canceled all of the Travis builds up to the last commit because speed.

**Comment by pippinsplugins** [comment]
@DrewAPicture Make sure to merge `release/1.9` back into `issue/854` once this is merged.

**Comment by DrewAPicture** [comment]
@pippinsplugins ayup! That's the plan :)

**Pull request merged**
