### PR TITLE
Issue/609 (revised)

### PR DESCRIPTION
**Pull request by fjarrett**
This PR extends what was done in #700 for #609 in light of [this decision](https://github.com/affiliatewp/AffiliateWP/pull/790#issuecomment-123927628) made recently in #624.

I also went ahead and changed to using a `affwp_` prefix for the custom setting key rather than `gform_`. The latter makes it sound like it's a setting coming from Gravity Forms. I think it's more appropriate to use our prefix here. Let me know if you agree @pippinsplugins.

### CODE REVIEW

**Comment by fjarrett** [comment]
@pippinsplugins Ready for review.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by fjarrett** [comment]
Oops I need to change the update script as well. Will do that now.

**Comment by fjarrett** [comment]
Done

**Comment by fjarrett** [comment]
@pippinsplugins Conflicts resolved

**Pull request merged**
