### PR TITLE
WP-Invoice Integration

### PR DESCRIPTION
**Pull request by antonkorotkov**

### CODE REVIEW

**Comment by uderic** [comment]
Let us know if you have any questions about WP-Invoice or the functionality we included. Cheers!

**Comment by pippinsplugins** [comment]
@antonkorotkov @uderic does WP Invoice handle refunds?

**Comment by antonkorotkov** [comment]
@pippinsplugins not automatically

**Comment by pippinsplugins** [comment]
Can an invoice be marked as refunded by an admin?

**Comment by antonkorotkov** [comment]
Yes

**Comment by pippinsplugins** [comment]
@antonkorotkov Could you add support for revoking referrals when an invoice is refunded? See this for an example: 

https://github.com/affiliatewp/AffiliateWP/blob/master/includes/integrations/class-edd.php#L21

https://github.com/affiliatewp/AffiliateWP/blob/master/includes/integrations/class-edd.php#L304

**Comment by antonkorotkov** [comment]
Ok, sure

**Comment by pippinsplugins** [comment]
:+1:

**Comment by antonkorotkov** [comment]
@pippinsplugins refunds handled.

**Comment by pippinsplugins** [comment]
@antonkorotkov excellent! We get this included in one of the upcoming releases!

**Comment by uderic** [comment]
Thanks @pippinsplugins!

**Pull request merged**
