### PR TITLE
Issue/2160

### PR DESCRIPTION
**Pull request by pippinsplugins**
Set debug property to correct value for backwards compatibility.
Remove debug check in log method.
Use utilities class in log() method.

Issue: #2160

### CODE REVIEW

**Comment by DrewAPicture** [comment]
I don't see a need to retain checking `$this->debug` all over the place if `$this->log()` (via the global method) now checks it also. Absolutley retain the value for back-compat but it's now moot.

**Comment by DrewAPicture** [comment]
Let's remove the `$this->debug` checks in 2.1.

**Comment by pippinsplugins** [comment]
@DrewAPicture I agree. They should be removed from all integrations. I started to do it here but then decided to keep this PR limited to the bug fix itself.

**Comment by DrewAPicture** [comment]
Added two tests to demonstrate `debug` property back-compat.

**Pull request merged**
