### PR TITLE
Add Formidable Pro integration. Resolve #463

### LINKED ISSUE #463: Formidable Pro integration
We should consider adding support for Formidable Pro: https://formidablepro.com/

### PR DESCRIPTION
**Pull request by naomicbush**

### CODE REVIEW

**Comment by sumobi** [comment]
@naomicbush oh awesome! :+1:

**Comment by pippinsplugins** [comment]
Sweet! I'll pick up a copy of Formidable Pro to test with before we push it out.

**Comment by pippinsplugins** [comment]
#463

**Comment by sumobi** [comment]
:+1:

**Comment by pippinsplugins** [comment]
I've manually merged this into `issue/463` for further testing / tweaks. Thanks @naomicbush !

**Pull request closed without merging**
