### PR TITLE
Add documentation for AffiliateWP 1.9

### PR DESCRIPTION
**Pull request by ramiabraham**

### CODE REVIEW

**Comment by ramiabraham** [comment]
(Merging in 1.9 now to resolve conflicts)

**Comment by ramiabraham** [comment]
PR added for first of two steps required to resolve conflicts:
https://github.com/AffiliateWP/AffiliateWP/pull/1644

**Comment by pippinsplugins** [comment]
@ramiabraham looks like it's still conflicting.

**Comment by ramiabraham** [comment]
@pippinsplugins After that PR, I have to merge in 1.9 again in to /docs/1.9

**Comment by ramiabraham** [comment]
(Will create separate PR against master)

**Pull request closed without merging**
