### PR TITLE
Issue/711

### LINKED ISSUE #711: Add affiliate's username to Edit Affiliate screen
It would be nice to be able to see the affiliate's username on the `Edit Affiliate` screen, in the same fashion as the User ID:

screen shot 2015-05-28 at 12 27 37 pm

### PR DESCRIPTION
**Pull request by sumobi**
Fixes #711

### CODE REVIEW

**Comment by pippinsplugins** [comment]
`$user_info->data->user_login` should just be `$user_info->user_login`. Why the `data` object?

**Comment by sumobi** [comment]
@pippinsplugins user_login only exists in `data`

screen shot 2015-06-01 at 9 47 39 am

**Comment by pippinsplugins** [comment]
Ah, pretty sure it uses a magic method to let you retrieve it with
`$user_data->user_login` any way.

**Comment by sumobi** [comment]
Must be not so magic, that was the first thing I attempted but it returned null :)

**Comment by sumobi** [comment]
Actually I think you're right, it works now. My magic must have been failing before.

**Comment by pippinsplugins** [comment]
Ha ok then, merging as is :D

**Pull request merged**
