### PR TITLE
Add affwp_post_update() hook

### PR DESCRIPTION
**Pull request by sumobi**
Fixes: https://github.com/affiliatewp/AffiliateWP/issues/506

### CODE REVIEW

**Comment by sumobi** [comment]
@pippinsplugins if we can slip this in 1.5.2 that would be awesome

**Comment by pippinsplugins** [comment]
Yep, lets do it. Hoping to review / finish 1.5.2 tonight or tomorrow.

**Comment by pippinsplugins** [comment]
Since this will fire on all update calls, did you have a method in mind to distinguish the data type being updated?

**Comment by sumobi** [comment]
@pippinsplugins I don't yet, no. I was thinking we'd do the same as the add hook, but we'd need to pass in a type variable.

**Pull request merged**
