### PR TITLE
issue/955 – Show product results on shop page when accessed with a pretty referral URL

### PR DESCRIPTION
**Pull request by DrewAPicture**
Issue: #955 

Also strips pretty referral bits from pagination URLs when on the shop page.

### CODE REVIEW

**Comment by DrewAPicture** [comment]
@michaelbeil Let's give this one another test. Instead of trying to identify the referral bits, it simply grabs the pagination bits and rebuilds the paginated shop URL minus the referral bits.

**Comment by michaelbeil** [comment]
Tested both affiliate ID and username referral links and it works like a charm.

**Comment by digimarkup** [comment]
Since this has been added in version 1.8, I'm having problems with pagination on category pages. When clicking on the 'Page 3' link while on a category page, I'm now being sent to 

http://site.com/shop/page/3/ 

instead of 

http:/site.com/product-category/category

**Comment by DrewAPicture** [comment]
Hi @digimarkup, the fix for this issue is slated to be released with v1.8.1 of AffiliateWP, see #1277.

If you'd like more immediate assistance, I suggest contacting [AffiliateWP support](https://affiliatewp.com/support/).

**Comment by michaelbeil** [comment]
Product tags also need to be accounted for: #1289.

**Pull request merged**
