### PR TITLE
update Ninja Forms integration for compatibility with Ninja Forms THREE.

### PR DESCRIPTION
**Pull request by kjohnson**
Deprecated old methods with a Ninja Forms version check for backwards compatibility and added the new Ninja Forms action class for supporting Ninja Forms THREE (v3).

### CODE REVIEW

**Comment by pippinsplugins** [comment]
@kjohnson Will this action register automatically or does the site owner need to enable it (like MailChimp)?

**Comment by kjohnson** [comment]
The `Add Referral` Action will be available if the Ninja Forms integration is enabled in the AffiliateWP settings. It will not be added to the form automatically, but it can be added. This is apposed to adding the form setting convention in 2.x.

screenshot 2016-02-18 10 14 53

**Comment by ramiabraham** [comment]
In testing, I don't see any AffiliateWP fields being present, or any AffiliateWP functionality within NF3.

- Added code from this pull into https://github.com/AffiliateWP/AffiliateWP/tree/issue/1110
- Accounted for the corrected NF typo (https://github.com/wpninjas/ninja-forms/issues/1472)
- Results in db errors, root cause being a missing table `wp_nf3_field_meta` ( @kjohnson is this a known issue at all?)
- Using affwp at https://github.com/AffiliateWP/AffiliateWP/commit/06e059e330c17bdf5eabf7491c6e75b20dea44fd, NF:master at `70276324`

**Comment by kjohnson** [comment]
@ramiabraham the integration adds a new Form Action type to Ninja Forms [see above screenshot]. This new actions have settings for mapping the total, as well as settings for referrer email address, etc.

Also, the database tables are created when upgrading from NF2 to NF3. This can also be done by enabling "developer mode" and running "mock data", see http://developer.ninjaforms.com/codex/mock-data/

**Comment by ramiabraham** [comment]
Thanks @kjohnson. We were able to track the cause of referrals not being created to the `$reference` being a non-unique string (which is required in AffiliateWP).

I'd like to use the NF form submission ID as the unique string for referrals (instead of the datetime string placeholder in there now).

In NF 2.x, you could do something like:

`$ninja_forms_processing->get_form_setting( 'sub_id' )`

Do you know what the equivalent would be in NF3?

Looks like it's too early to query the object with the built-in NF3 methods, eg
`Ninja_Forms()->form()->sub($nf_sub_id )->get()`

(latest is https://github.com/AffiliateWP/AffiliateWP/commit/6e39ab51510788c898b8981ba7303aac4a706817)

**Comment by ramiabraham** [comment]
_(Closing in favor of https://github.com/AffiliateWP/AffiliateWP/pull/1421/)._

**Pull request closed without merging**
