### PR TITLE
i18n > New pot + updated pos + New French l10n

### PR DESCRIPTION
**Pull request by fxbenard**

### CODE REVIEW

**Comment by michaelbeil** [comment]
Thanks @fxbenard!

**Comment by pippinsplugins** [comment]
@fxbenard this was made against `master` which has now had `release/1.9` merged into it. That changes a lot of text strings. Any chance you're up for re-updating it?

**Comment by fxbenard** [comment]
@pippinsplugins I will do what's needed. No problem.

**Comment by fxbenard** [comment]
@michaelbeil @pippinsplugins Done ;)

**Comment by pippinsplugins** [comment]
Crud, new conflict after merging the lang file updates from @michaelbeil.

**Comment by fxbenard** [comment]
As we did it at the same time and you merged @michaelbeil commit first it created a new conflict. It's now solved on my side. I hope so ;)

**Pull request merged**
